### ISSUE TITLE
Selection of different output formats (json, xml)

### ISSUE THREAD

**Issue by upieper** [NuCivic/open_data_schema_map#17]
In our fork, I have created an option to select the output format when creating or editing an API. We needed to output the data in xml for a subset of the dataset content type. It would be great to get feedback on whether this would be general enough to eventually merge back. 

This is what I have been doing:

1. Added a field to the database for the output format
2. Change the install script (schema change, update section)
3. Created a 'select' form element with the options:
 * json (default)
 * json-pretty
 * xml
4. Added functions for xml serializing (I added the json-pretty functions earlier)

The main issue is the xml serializing. I am currently using the pear XML_serializer module, but it needs work, as the way a lot of the function calls are coded is deprecated, so the module generates a million error messages (but still does the job). 

Currently missing is:
1. settle on an xml serializer (fix XML_serializer or choose a different one, simplexml, ??, suggestions?) 
2. when "xml" has been selected, provide a field to enter the root element and the default tag
3. add behat tests

Please let me know any comments or suggestions.

**Comment by drkloc** [comment]
#31 will get this in. Closing.
