### ISSUE TITLE
Duplicate endpoint at module upgrade

### ISSUE THREAD

**Issue by upieper** [NuCivic/open_data_schema_map#19]
I had forked odsm at revision 46434afc6081699e342ece5b1cd932da1c12a243. 
After rebasing to HEAD on Friday, the ckan_revision_list endpoint now appears twice in ```admin/config/services/odsm```. 

Output of ```$list``` in ```function open_data_schema_map_api_load_all()```: 

```
array (
  0 => 'ckan_group_list',
  1 => 'ckan_package_list',
  2 => 'ckan_package_show',
  3 => 'ckan_revision_list',
  4 => 'data_json',
  5 => 'out_own_endpoint',
  6 => 'ckan_site_read',
  7 => 'ckan_revision_list',
  8 => 'ckan_package_revision_list',
)
```

The first entry comes from a database entry that was created in a previous version. 
The second entry is generated from code. 

Is the solution to this issue, to remove the endpoint from the database table? 
Should that have been done in the .install script?

**Comment by drkloc** [comment]
This issue was moved to NuCivic/dkan#416
